Allow automatic HTTP Basic authentication on device list pages
TasmoAdmin/TasmoAdmin pull request #758
Opened 2023-01-15 00:16 UTC by x-magic

It's a relatively simple hack here, as it just check if username and password is set, then add it to the URL for automatic login on Tasmota's web UI. 

I'm a bit confused when I go through the code if the user didn't set the username (which should be "admin" by default) but rather the password only. On my end the behaviour is that the username will be simply empty if I edit a device, but will fallback to "admin" if I leave the field empty at the time of adding a new device in `devices.csv`. Also it seems when there's no username at all in `devices.csv` Tasmota will refuse the connection as username is not provided. I guess if this issue can be addressed, the code in this PR can be further improved (allows auto-login when username is not provided). 

Welcome suggestions 😃

2023-01-15 09:46 UTC, inverse requested changes
First up thanks for taking the time to contribute! 

Def seems nice a nice way to speed up the HTTP basic authentication since TasmotaAdmin knows the credentials. 

Would it be possible to extract this logic into a class? e.g. similar to https://github.com/TasmoAdmin/TasmoAdmin/blob/master/tasmoadmin/src/Helper/ViewHelper.php

Then we can add some tests easier + reduce copying :)

2023-01-16 20:31 UTC, inverse commented
if you don't have time or need help i'm happy to help contribute?

2023-01-16 22:55 UTC, x-magic commented
> if you don't have time or need help i'm happy to help contribute?

Feel free to take it over :) Not sure if I'll have time recently. Though happy to follow up in the near future.

2023-01-17 20:43 UTC, merged

2023-01-17 20:44 UTC, inverse commented
Added tests and kept it DRY in https://github.com/TasmoAdmin/TasmoAdmin/pull/765

Probably the device model makes sense in this instance :)